[package]
name = "mikanos_usb"
version = "0.1.0"
edition = "2018"
build = "build.rs"
links = "mikanos_usb"

[build-dependencies]
cc = "1.0.67"
flate2 = "1.0.20"
glob = "0.3.0"
reqwest = "0.11.3"
tar = "0.4.33"
tokio = { version = "1.5.0", features = ["macros", "rt-multi-thread"] }
